package internal

// Reason
const (
	ERR_OUT_OF_RANGE              = "out of range"
	ERR_NON_NEGATIVE_DURATION     = "should be a non-negative time.Duation"
	ERR_NON_NEGATIVE_INTENGER     = "should be a non-negative integer"
	ERR_NON_NEGATIVE_NUMBER       = "should be a non-negative number"
	ERR_NON_ZERO                  = "should not be zero"
	ERR_NON_UTC                   = "should be a UTC time"
	ERR_NAN_OR_INFINITY           = "cannot be -inf, +inf or NaN"
	ERR_NIL                       = "cannot be nil"
	ERR_EMPTY_ARRAY               = "cannot be an empty array"
	ERR_EMPTY_STRING              = "cannot be an empty string"
	ERR_NOT_ARRAY                 = "should be an array"
	ERR_INVALID_CAST_TYPE         = "cannot cast '%T' to '%T'"
	ERR_INVALID_DURATION          = "specified time.Duration %s is invalid"
	ERR_INVALID_INTEGER           = "specified integer %d is invalid"
	ERR_INVALID_FLOAT             = "specified number %v is invalid"
	ERR_INVALID_NUMBER            = "specified number %q is invalid"
	ERR_INVALID_STRING            = "specified string %q is invalid"
	ERR_INVALID_VALUE             = "specified value %v is invalid"
	ERR_INVALID_IP_ADDR           = "specified ip address %v is invalid"
	ERR_INVALID_TIME              = "specified time %v is invalid"
	ERR_STRING_TOO_LONG           = "specified string is too long"
	ERR_STRING_TOO_SHORT          = "specified string is too short"
	ERR_UNSUPPORTED_CAST_IP_ADDR  = "cannot convert to net.IP from %T"
	ERR_UNSUPPORTED_CAST_TIME     = "cannot convert to time.Time from %T"
	ERR_UNSUPPORTED_CAST_DURATION = "cannot convert to time.Duration from %T"
	ERR_INVALID_REGEX_PATTERN     = "specified reguler expression pattern %q is invalid"
)
